---
- name: Instalar Docker no Ubuntu
  hosts: vm
  become: true
  gather_facts: false 

  pre_tasks:
    - name: Preparar ambiente e instalar Python 3.9
      raw: |
        export DEBIAN_FRONTEND=noninteractive
        sudo fuser -vki /var/lib/dpkg/lock-frontend || true
        sudo apt-get update && \
        sudo apt-get install -y python3.9 python3.9-distutils
      changed_when: false

    - name: Coletar fatos do sistema
      setup: # Removido qualquer parâmetro interno para evitar o erro de "Unsupported parameters"

  tasks:
    - name: Instalar dependências do sistema
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present
        update_cache: true

    - name: Adicionar chave GPG oficial do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório do Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Instalar Docker e Pip
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - python3-pip
        state: present
        update_cache: true

    - name: Instalar SDK do Docker para Python
      pip:
        name: docker
        executable: pip3

    - name: Adicionar usuário ao grupo Docker
      user:
        name: "{{ ansible_user | default('azureuser') }}"
        groups: docker
        append: true

    - name: Garantir que o Docker está rodando
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Executar container da aplicação Java
      docker_container:
        name: java-api
        image: iesodias/java-api:latest
        state: started
        pull: true
        restart_policy: always
        published_ports:
          - "8081:8081"