---
- name: Instalar Docker no Ubuntu
  hosts: vm
  become: true
  gather_facts: false 

  pre_tasks:
    - name: Preparar ambiente, Python 3.9 e bibliotecas APT
      raw: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update
        sudo apt-get install -y python3.9 python3.9-distutils python3-apt
      changed_when: false

    - name: Coletar fatos do sistema
      setup:

  tasks:
    - name: Instalar dependências do sistema
      # Usamos shell aqui para evitar dependência do módulo python-apt do Ansible
      shell: |
        apt-get update && \
        apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release software-properties-common
      args:
        warn: false

    - name: Adicionar chave GPG oficial do Docker
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg --yes
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Adicionar repositório do Docker
      shell: |
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Instalar Docker e Pip
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - python3-pip
        state: present
        update_cache: true

    - name: Instalar SDK do Docker para Python
      pip:
        name: docker
        executable: pip3

    - name: Adicionar usuário ao grupo Docker
      user:
        name: "{{ ansible_user | default('azureuser') }}"
        groups: docker
        append: true

    - name: Garantir que o Docker está rodando
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Executar container da aplicação Java
      docker_container:
        name: java-api
        image: iesodias/java-api:latest
        state: started
        pull: true
        restart_policy: always
        published_ports:
          - "8081:8081"